# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KGqtNvdSzehC7HrqXbwgTBx16seLnoa_
"""

import numpy as np

# --- PEGA AQUÍ UNO DE TUS ARRAYS DE COEFICIENTES EN FLOAT ---
coeficientes_float = [
  (agregar aquí todos los coeficientes)
]
# -------------------------------------------------------------

# Convertimos los floats a formato Q15
# La fórmula es: q15 = int(float * 2^15)
coeficientes_q15 = np.round(np.array(coeficientes_float) * 32767).astype(np.int16)

linea = "    "
for i, coef in enumerate(coeficientes_q15):
    linea += f"{coef}, "
    if (i + 1) % 14 == 0:  # Imprime 14 coeficientes por línea
        print(linea)
        linea = "    "
if linea.strip() != "":
    print(linea)